### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by carlos-mg89** [browniefed/pdxlivebus#5]
I'm trying to make the project run but can't really manage to do it. There's a naming collision:

```
Failed to build DependencyGraph: Naming collision detected: /home/carlos/workspace/pdxlivebus/node_modules/fbjs/package.json collides with /home/carlos/workspace/pdxlivebus/node_modules/create-react-class/node_modules/fbjs/package.json
Error: Naming collision detected: /home/carlos/workspace/pdxlivebus/node_modules/fbjs/package.json collides with /home/carlos/workspace/pdxlivebus/node_modules/create-react-class/node_modules/fbjs/package.json
at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:112:32
    at tryCallOne (/home/carlos/workspace/pdxlivebus/node_modules/promise/lib/core.js:37:12)
    at /home/carlos/workspace/pdxlivebus/node_modules/promise/lib/core.js:123:15
    at flush (/home/carlos/workspace/pdxlivebus/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pdxlivebus@1.0.0 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pdxlivebus@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

To get here, I have executed first "npm install", and then "npm start", where I got this error.

**Comment by browniefed** [comment]
This is very very very outdated. An entire rework of everything is in the works over here https://github.com/codedailyio/pdxlivebus

Focusing first on the app then on the web version. It uses https://expo.io

**Comment by browniefed** [comment]
This repo will get updated once the code is of parity/bettter
